### ISSUE TITLE
Tools stops when image size is smaller than derivative.

### ISSUE THREAD

**Issue by timinaust** [sshambar/BatchCustomDerivatives#1]
Hi - thanks for this great extension.

I was using it to pre-create all the derivatives but it stopped at one point and failed to restart.  I found that the problem occurred when it attempts to create a medium size derivative for an image that was smaller than that for 'medium' (*-me.jpg).  

Looking at i.php, and a packet trace it appears to return a 302 relative redirect to the original image (*.jpg) when this is smaller than the requested derivative, and LWP::Useragent is not handling this correctly.  This works first time because it skips over the error, but next time you run it, it bails at line 290 because this is an error on the first one it finds.

First head request is to 
    http://127.0.0.1/piwigo/i.php?galleries/x/y/image-me.jpg

The redirect response is 302-Found with location '././galleries/x/y/image.jpg

LWP::Useragent then automatically creates second head request to 
    http://127.0.0.1/piwigo/galleries/x/y/galleries/x/y/image.jpg

This returns 'not found'. 

I would expect the redirect to go to http://127.0.0.2/piwigo/././galleries/x/y/image.jpg but it looks like the query parameters are confusing it.

I am not a 'perl' person, but I did find this https://www.perlmonks.org/?node_id=806051

Given that your code doesn't actually need to perform the redirect, it may be easiest to either stop LWP redirecting or add a handler to trap the redirect.

My quick fix was to comment out the 'bail'.  Further research show that this may only occur when metadata (height and width) doesn't exist yet.

**Comment by sshambar** [comment]
Thanks for investigating this... I'll see if I can create/test a fix and get a new release out as soon as I can.

**Comment by sshambar** [comment]
Sorry this took so long, life has it's distractions ;)

Let me know if the updated version of the tool works (0.3.0)... if so, I'll create a release.

**Comment by sshambar** [comment]
Version 0.3.0 should fix the issue :)
